Feature/implement code model
xszym/UMCS-lights pull request #15
Opened 2021-03-15 21:27 UTC by dorotajulia

2021-03-15 21:37 UTC, mprostakk requested changes

2021-03-15 21:37 UTC, mprostakk commented on .gitignore
> +backend/codes/migrations/*
Migracje powinny być zostawiane ogólnie, więc o tą liiniijkę bym usunął 👯 

Migracje są przydatne w wypadku kiedy model się zmienia, a baza już ma sporo danych i kodem możemy modyfikować te dane.

2021-03-15 21:37 UTC, mprostakk commented on backend/codes/admin.py
> +admin.site.register(CustomUser)
Dobrze, zapomniałem o tym :)

2021-03-15 21:37 UTC, mprostakk commented on backend/codes/models.py
> +    id = models.IntegerField(primary_key=True)
Nie wiem czy id jest potrzebne w sumie, id oraz pk robią się automatycznie w modelach django, chyba że się mylę

2021-03-15 21:49 UTC, xszym approved these changes
GJ @dorotajulia

2021-03-16 18:59 UTC, mprostakk commented on backend/.env.dev
> +POSTGRES_DB=postgres
to może zostać, ważne żeby było w .env.dev

2021-03-16 18:59 UTC, mprostakk approved these changes

2021-03-16 18:59 UTC, merged