Fix random color during fadeout_in
xszym/UMCS-lights pull request #69
Opened 2021-05-21 14:48 UTC by xszym

Ogólnie to multiply miał wartość na minusie przez 1 klatkę, wtedy wartości dmx wchodziły na minus i przez to to losowe zachowanie. 

Nie było też zapisywania "zerowej" sceny do redisa po wygaśnięciu, co dodałem przy okazji :)

2021-05-21 15:18 UTC, mprostakk requested changes

2021-05-21 15:18 UTC, mprostakk commented on emulate/sender.py
> +	multiplier = 0.0 if multiplier < 0.0 else multiplier
Można chyba czytelniej zrobić
```
max(0.0, multiplier) 
```

2021-05-21 15:18 UTC, mprostakk commented on emulate/sender.py
> +	if multiplier = save_to_redis_treshold:
if ma tylko jedno = !!!!!!
przypisujesz tutaj w tym miejscu !!!!

2021-05-21 16:37 UTC, mMosiur commented on emulate/sender.py
> +	if multiplier = save_to_redis_treshold:
Python się na tym nie wykrzaczy?

2021-05-21 17:17 UTC, xszym commented on emulate/sender.py
> +	if multiplier = save_to_redis_treshold:
Dziwne lokalnie działało :D

2021-05-22 10:23 UTC, mprostakk approved these changes

2021-05-23 08:39 UTC, mMosiur approved these changes

2021-05-23 08:39 UTC, merged